export { default as Splashscreen } from './Splashscreen';
export { default as Onboardingscreen } from './Authscreens/Onboardingscreen';
export { default as Loginscreen } from './Authscreens/Loginscreen';
export { default as Signupscreen } from './Authscreens/Signupscreen';
export { default as Homescreen } from './Appscreens/Homescreen';
export { default as Searchscreen } from './Appscreens/Searchscreen';
export { default as Portfolioscreen } from './Appscreens/Portfolioscreen';
export { default as Profilescreen } from './Appscreens/Profilescreen';
// export { default as Homescreen } from './Appscreens/Homescreen';
// export { default as Homescreen } from './Appscreens/Homescreen';
// export { default as Homescreen } from './Appscreens/Homescreen';
// export { default as colors } from './colors';